### ISSUE TITLE
Los procesos deberian de tener la cantidad, no las lineas de produccion

### ISSUE THREAD

**Issue by A-deLuna** [elWizardz/proyectopa#2]

**Comment by A-deLuna** [comment]
yo estoy quitando esto de las lineas de produccion en el issue #1, alguien que se quiera aventar esto para los procesos? @Just-Ic3 @Glomels @jlvivero.
Hay que editar el modelo de procesos y el html

**Comment by jlvivero** [comment]
I'll do this

**Comment by jlvivero** [comment]
Places I'm changing this, models/forms/views
maybe html as well
