### ISSUE TITLE
Creating a new production line doesn't allow you to select process 

### ISSUE THREAD

**Issue by jlvivero** [elWizardz/proyectopa#4]
When you create a production line you should be able to add as many process as you can (be able to add them in the first place) in a specific order  

Things that should include when creating a new production line:  
- Name(it's already there)  
- list of process:  
- add new process (that will show you a list of process again except for the ones already chosen)  

To solve this issue we need to make the database relate to each other, and make the forms and then change the html to reflect the change  

files that most likely need change:  
- models.py  
- forms.py  
- templates/lineasdeproduccion_agregar.html

**Comment by jlvivero** [comment]
anyone wants to be assigned to this?
@A-deLuna , @Just-Ic3 , @Glomels

**Comment by A-deLuna** [comment]
I'm doing this in #1

**Comment by jlvivero** [comment]
this is fixed in #1 except for a bug in  #7  but that's adressed somewhere else, closing this
