### ISSUE TITLE
Al querer editar una linea de produccion no es posible agregarle mas de un elemento

### ISSUE THREAD

**Issue by A-deLuna** [elWizardz/proyectopa#7]
este bug lo introduje en #6 , el codigo responsable esta en views.py, 
https://github.com/elWizardz/proyectopa/blob/master/proyectopaapp/views.py#L101

aqui deberia de estar sacando los procesos seleccionados y guardarlos en el objeto de linea de produccion.

**Comment by jlvivero** [comment]
acabo de probar y tienes que hacer ctrl click para seleccionar mas de dos, no se si haya alguna manera de arreglar eso.
(eso es solo cuando agregas el bug sigue siendo un problema)

**Comment by A-deLuna** [comment]
arreglado en el commit  0dbde43 de vivero
