### ISSUE TITLE
Hacer la funcionalidad de los procesos en el tiempo

### ISSUE THREAD

**Issue by A-deLuna** [elWizardz/proyectopa#9]
Okay, ahorita como lo tenemos pensado es que tengamos estos nuevos objetos de la clase Instancia
que saben de que orden provienen , en que proceso estan actualmente y una lista de los procesos que le siguen. 

Luego tendremos codigo que se encargue de manejar la lista de espera de cada proceso, este codigo recibira las instancias y les actualizara el proceso actual a como sea necesario.

**Comment by A-deLuna** [comment]
#10 se encarga de meter la clase instancia pero le falta la lista de los procesos que le sigue y el codigo que maneje los timeouts

**Comment by A-deLuna** [comment]
en #11 se agrego el codigo que maneja los timeouts, los procesos ya siguen su caminito pero aun no estoy seguro de que hacer con la instancia cuando termina de recorrer los procesos

**Comment by jlvivero** [comment]
solved en #11 falta contar los procesos terminados pero eso sera en los views
